### ISSUE TITLE
mysqlstats  undefined value at mysqlstats.pl line 129.

### ISSUE THREAD

**Issue by bmfmancini** [bernisys/cacti-templates#2]
[root@master1 scripts]# perl mysqlstats.pl
DBI connect('database="cacti";host="localhost";port="3306";mysql_connect_timeout=2','"cacti"',...) failed: Unknown MySQL server host '"localhost"' (-2) at mysqlstats.pl line 82.
Can't call method "prepare" on an undefined value at mysqlstats.pl line 129.
[root@master1 scripts]#

**Comment by bernisys** [comment]
Hmm this is strange. It is working on our installation on all pollers.
I see though, that you use "localhost" as the DB declaration in cacti. We use the interfaces' IP addresses (we need to, as we use a distributed cacti setup), maybe that could be the cause.
Did you check with "netstat -an" if the SQL daemon is actually listening to a web socket on 3306 tcp?
It might be that if you only use a single poller instance with "localhost" as DB host, cacti might use a local socket instead of a web socket. If that is the case, you might need to check your sql daemon configuration.

Assuming you have checked that can connect manually to the server using the mysql shell command, here are some ideas:

What happens if you use 127.0.0.1 instead of localhost?
I believe i had read somewhere else, that for example the mysql client command on the shell might use the local socket instead of a web socket to connect to the DB - this could cause some problems.


Can you please try to connect again with a slight change in the code?

In the function cacti_db_open, change line 83, drop the "port" parameter:
```
    "DBI:mysql:database=$ref_params->{'default'};host=$ref_params->{'hostname'};mysql_connect_timeout=2",
```

This might make it use a local socket instead of  a web socket.
If this works, just tell me and i will add a check that drops the port in this situation.

**Comment by seanmancini** [comment]
Tried to change from localhost to 127.0.0.1 but no go 

here is the output 

```
[root@master1 scripts]# perl mysqlstats.pl
DBI connect('database="cacti";host="127.0.0.1";mysql_connect_timeout=2','"cacti"',...) failed: Unknown MySQL server host '"127.0.0.1"' (-2) at mysqlstats.pl line 82.
Can't call method "prepare" on an undefined value at mysqlstats.pl line 130.
```

**Comment by bmfmancini** [comment]
Tried to change from localhost to 127.0.0.1 but no go 

here is the output 

```
[root@master1 scripts]# perl mysqlstats.pl
DBI connect('database="cacti";host="127.0.0.1";mysql_connect_timeout=2','"cacti"',...) failed: Unknown MySQL server host '"127.0.0.1"' (-2) at mysqlstats.pl line 82.
Can't call method "prepare" on an undefined value at mysqlstats.pl line 130.
```

**Comment by bmfmancini** [comment]
I get farther when I hard code the database credentials but then I get 

[root@master1 scripts]# perl  mysqlstats.pl
DBD::mysql::st execute failed: No database selected at mysqlstats.pl line 130.
DBD::mysql::st fetchall_hashref failed: statement contains no result [err was 4 now 2000000000]
Field 'count' does not exist (not one of ) at mysqlstats.pl line 131.
Can't use an undefined value as a HASH reference at mysqlstats.pl line 99.


So maybe a regex issue on  between the script and config.php ?
still  debugging

**Comment by bmfmancini** [comment]
OK yes need to change 

```
  my $handle = DBI->connect(
    "DBI:mysql:database=$ref_params->{'default'};host=$ref_params->{'hostname'};port=$ref_params->{'port'};mysql_connect_timeout=2",
    $ref_params->{'username'},
    $ref_params->{'password'}
  );
```

to

```
  my $handle = DBI->connect(
    "DBI:mysql:database=$ref_params->{'database_default'};host=$ref_params->{'database_hostname'};port=$ref_params->{'database_port'};mysql_connect_timeout=2",
    $ref_params->{'database_username'},
    $ref_params->{'database_password'}
  );
```

That fixes the DB connection issue and just leave the DB selection error

**Comment by bmfmancini** [comment]
OK ive tried 127.0.01 as well as the host IP 192.168.x.x same thing funny error unknown database server ??
manually via mysql shell I am able to access the DB without issue

**Comment by bmfmancini** [comment]
I got it working !

My suspicion was correct there is something wrong with the regex 


sub cacti_config_get_db_params {
  my $file = shift;

  $file = $CACTI_CONF_FILE if (!defined $file);

  my %params;

  open(my $h_file, '<', $file);
  while (my $line = <$h_file>) {
    next if $line !~ /\$r?database/;
    next if $line =~ /^\s*#/;
    if ($line =~ /^\s*\$(r?)database_(\w+)\s+=\s+'?(.*?)'?;/)
    {
      $params{$1}{$2} = $3;
    }
  }
  return %params;
}

the regex needs to be updated not to include the encapsulating " " around each value in the config file i.e
$database_default = "cacti";
should just pull cacti  in my case I found the script outputting
DBI connect('database="cacti";host=;mysql_connect_timeout=2','"cacti"',

Went into config.php and remove the " " around the username,password,hostname etc and bingo working
This works now but in future versions of PHP this will cause an issue 

``
[Fri Jul 30 16:59:09.555770 2021] [php7:warn] [pid 4045] PHP Warning:  Use of undefined constant cacti - assumed 'cacti' (this will throw an Error in a future version of PHP) in /var/www/html/cacti/include/config.php on line 33, referer: http://192.168.1.194/cacti/clog.php
```

**Comment by bernisys** [comment]
Glad you got it working and many thanks for analyzing this so deeply! This will help getting the script into a more usable state.

I think i should change the way i am parsing the cacti config a bit, so that it takes the different quotes into account. I wanted to make it easy and to avoid having to adapt credentials in several places, when there is everything in that rather central config file. But some use single quotes and some apparently use double quotes. I usually use singles, as they treat strings as literals and this reduces the effort of escaping special characters. It became a habit of mine when i program in perl, but i just checked, and apparently PHP uses the same interpretation. And as in my case the PHP code for the configuration contains only single quotes, i wrote my little program to parse only singles. And if the quotes are parsed properly, then i believe the rest of the code should also work much better.

p.S.
If you're not using any single quotes in the DB passwords, you should just change the double quotes in the config to single ones, this should make it working and PHP not croaking about future versions.

**Comment by bmfmancini** [comment]
@bernisys  I use double quotes in my config.php which has always seemed to make PHP happy 
I think either ' or " will make php happy

Still trying to find a good regex to fix it as I think most users will use either ' or " in their configs
